### PR TITLE
(pending) Releases - add Struts 2.5.14.1 to Prior Releases, that has no Vulnerabilities; dates for 2.3.x

### PR DESCRIPTION
**Pull request by paulvi**

### CODE REVIEW

**Comment by lukaszlenart** [comment]
These are only the prior releases, not the current release. I'm not convinced that the current release should be on the list

**Comment by paulvi** [comment]
But http://struts.apache.org/announce.html says
>Struts 2.5.14.1 General Availability

**Comment by lukaszlenart** [comment]
You lost me, the page doesn't link to `/downloads.html` but just to `/download.cgi` aka `/download.html`. When you open http://struts.apache.org/downloads.html at top you have the current release and below there is a list of prior releases. 2.5.14.1 is the current release and it shouldn't be listed under the Prior releases. It also doesn't contain any vulnerabilities as far I know.

**Comment by paulvi** [comment]
Oh, right.

Logically 2.5.14.1 is current releases, so this should be added after next release

**Comment by paulvi** [comment]
I can add "current recommended 2.5.x release" and "current recommended 2.3.x release"
to make it inline with intro above table.

> As a courtesy, we retain archival copies of the website for releases that initially were considered "General Availability" but which has been reclassified as "Not recommended" since they contain security issues

**Comment by lukaszlenart** [comment]
hm... I cannot imaging what do you mean by that so please prepare a PR :)

**Comment by paulvi** [comment]
That is done in https://github.com/apache/struts-site/pull/65/commits/a8f054fbd3f4592b56bf695028b43bbf80ef0522

**Comment by lukaszlenart** [comment]
Ok, I see now but I'm still not convinced - this mixes two different things and we do not recommend using 2.3.x, even the latest release

**Comment by paulvi** [comment]
OK, word "recommended" can be removed for 2.3.x  

but still the table is not yet seen as to contain the latest as well.

Now, where a user can quickly check if current best version has known Vulnerabilities? (with one click)  
Where exactly this Security Bulletin is?

**Comment by lukaszlenart** [comment]
The current version should never have known vulnerabilities, we do not publish them till we are not able to release a new version which addresses the reported vulnerabilities.

This table should give users a quick overview how vulnerable its current Struts version is, putting the current release in the same row gives a false picture that this version is vulnerable as well.

**Comment by paulvi** [comment]
OK

**Comment by lukaszlenart** [comment]
The missing days were addressed in #111

**Comment by lukaszlenart** [comment]
Thanks a lot!

**Pull request closed without merging**
