### PR TITLE
Removes founded snippets with fetched contents

### PR DESCRIPTION
**Pull request by yasserzamani**
`snippet.rb` has replaced all snippets with fetched content if it could successfully fetch and found from specified url. Also keeps current snippet markup in a comment for future if needed :)

### CODE REVIEW

**Comment by lukaszlenart** [comment]
Astonish work 👍

**Comment by yasserzamani** [comment]
Thank you! :) Glad to hear it.

**Comment by lukaszlenart** [comment]
Just noticed [this](https://github.com/apache/struts-site/edit/master/source/core-developers/postback-result.md) - do you know what's wrong?

**Comment by yasserzamani** [comment]
Yes. I kept that snippets not changed when could not being resolved (due to not found url or id). In above case, `snippet.rb` tries to fetch from (https://gitbox.apache.org/repos/asf?p=struts.git;a=blob_plain;f=core/src/main/java/org/apache/struts2/dispatcher/PostbackResult.java;hb=HEAD)[https://gitbox.apache.org/repos/asf?p=struts.git;a=blob_plain;f=core/src/main/java/org/apache/struts2/dispatcher/PostbackResult.java;hb=HEAD] but gets 404.

They are known and are a few as below:
```text
START SNIPPET: javadoc not found in https://gitbox.apache.org/repos/asf?p=struts.git;a=blob_plain;f=core/src/main/java/org/apache/struts2/components/DateTextField.java;hb=HEAD
START SNIPPET: example not found in https://gitbox.apache.org/repos/asf?p=struts.git;a=blob_plain;f=core/src/main/java/org/apache/struts2/components/DateTextField.java;hb=HEAD
START SNIPPET: javadoc not found in https://gitbox.apache.org/repos/asf?p=struts.git;a=blob_plain;f=core/src/main/java/org/apache/struts2/components/Div.java;hb=HEAD
START SNIPPET: javadoc not found in https://gitbox.apache.org/repos/asf?p=struts.git;a=blob_plain;f=core/src/main/java/org/apache/struts2/components/DateTextField.java;hb=HEAD
START SNIPPET: example not found in https://gitbox.apache.org/repos/asf?p=struts.git;a=blob_plain;f=core/src/main/java/org/apache/struts2/components/DateTextField.java;hb=HEAD
START SNIPPET: javadoc not found in https://gitbox.apache.org/repos/asf?p=struts.git;a=blob_plain;f=core/src/main/java/org/apache/struts2/components/Div.java;hb=HEAD
START SNIPPET: description not found in https://gitbox.apache.org/repos/asf?p=struts.git;a=blob_plain;f=core/src/main/java/org/apache/struts2/dispatcher/PostbackResult.java;hb=HEAD
START SNIPPET: params not found in https://gitbox.apache.org/repos/asf?p=struts.git;a=blob_plain;f=core/src/main/java/org/apache/struts2/dispatcher/PostbackResult.java;hb=HEAD
START SNIPPET: example not found in https://gitbox.apache.org/repos/asf?p=struts.git;a=blob_plain;f=core/src/main/java/org/apache/struts2/dispatcher/PostbackResult.java;hb=HEAD
START SNIPPET: visitorValidatorsExample not found in https://gitbox.apache.org/repos/asf?p=struts.git;a=blob_plain;f=apps/showcase/src/main/resources/org/apache/struts2/showcase/validation/VisitorValidatorsExampleAction-submitVisitorValidatorsExamples-validation.xml;hb=HEAD
START SNIPPET: description not found in https://gitbox.apache.org/repos/asf?p=struts.git;a=blob_plain;f=core/src/main/java/org/apache/struts2/dispatcher/VelocityResult.java;hb=HEAD
START SNIPPET: params not found in https://gitbox.apache.org/repos/asf?p=struts.git;a=blob_plain;f=core/src/main/java/org/apache/struts2/dispatcher/VelocityResult.java;hb=HEAD
START SNIPPET: example not found in https://gitbox.apache.org/repos/asf?p=struts.git;a=blob_plain;f=core/src/main/java/org/apache/struts2/dispatcher/VelocityResult.java;hb=HEAD
```
I will fix them as soon as possible :)

**Comment by lukaszlenart** [comment]
oh! superb!

**Pull request merged**
