### PR TITLE
Fixes all indents by an algorithm

### PR DESCRIPTION
**Pull request by yasserzamani**
# Algorithm

- Splits content to extract what will be between `<h1>`s
- Compute the minimum indent between `<h1>`s
- If minimum indent is bigger than 2, then decreases all indents between `<h1>`s till satisfy this rule

# Known Issues

Does not fix if indents are not sorted between `<h1>`s e.g. `#` then `###` then `##` (minimum is 2 and assumes it is ok)

# Functor code

```ruby
Jekyll::Hooks.register :pages, :pre_render do |page|
  fileName = "source/" + page.path
  unless File.exist?(fileName)
    puts "**************FILE NOT FOUND: "+fileName
    next 0
  end
  unless fileName.end_with?(".md")
    next 0
  end
  pcs = {}
  modified = false
  fileContent = File.binread(fileName)
  loop do
    pcs = fileContent.split(/(^\#\s[^\#\n]+$)/)    #splits by <h1>
    break if pcs.size > 2   # is <h1> biggest header?
    fileContent.gsub!(/^\#(\#+)(\s[^\#\n]+$)/,'\1\2')  #decreases all indents by one
    modified = true
  end
  unless pcs.size > 2
    puts "**************SKIPPED FILE: "+fileName
    next 0
  end
  unless pcs[1] =~ /^\#\s[^\#\n]+$/
    puts "**************UNKNOWN FILE: "+fileName
    next 0
  end
  i = 2
  while i < pcs.size
    pcsis = pcs[i].split(/(^\#\#+\s[^\#\n]+$)/)    #splits by <h{2,n}>
    j = 0
    unless pcsis[j] =~ /^\#\#+\s[^\#\n]+$/
      j = j + 1
    end
    minIndent = 99
    while j < pcsis.size
      spaceIndex = pcsis[j].index(' ')
      if spaceIndex < minIndent
        minIndent = spaceIndex
      end
      j = j + 2
    end
    if minIndent < 99
      delta = minIndent - 2
      if delta > 0
        pcs[i].gsub!(/^\#{#{delta}}(\#+)(\s[^\#\n]+$)/,'\1\2')  #decreases all indents by delta
        modified = true
      end
    end
    i = i + 2
  end
  if modified
    File.open(fileName, "wb") {|file|
      file.puts pcs.join
      file.close
    }
    puts "**************CORRECTED FILE: "+fileName
  end
end
```

### CODE REVIEW

**Comment by yasserzamani** [comment]
Oddly Ruby has changed new line characters in a few places. Could you set GitHub to ignore new line character changes when merges?

**Comment by lukaszlenart** [comment]
No, I cannot but you can do it yourself https://help.github.com/articles/dealing-with-line-endings/

**Comment by yasserzamani** [comment]
Thank you, I already had those. It seems IntelliJ had added those new lines at end of some files when thay are not ended with a new line. I reverted them manually and pushed a new commit :) fixed

**Comment by lukaszlenart** [comment]
LGTM 👍

**Pull request merged**
