### PR TITLE
gs - show full web.xml and its location

### PR DESCRIPTION
**Pull request by paulvi**
show full web.xml and its location

full `web.xml` is taken from https://github.com/apache/struts-examples/blob/master/basic-struts/src/main/webapp/WEB-INF/web.xml

### CODE REVIEW

**Comment by lukaszlenart** [comment]
👍

**Comment by paulvi** [comment]
In Step 5 http://struts.apache.org/getting-started/how-to-create-a-struts2-web-application.html#step-5---add-struts-2-servlet-filter

There is missing link for web.xml. It reads as

> For more information about configuring the deployment descriptor for Struts 2 see web.xml.

**Comment by yasserzamani** [comment]
You're right 👍  It should be `[web.xml](/core-developers/web-xml.html)` (without `).

**Comment by paulvi** [comment]
@yasserzamani thanks

**Comment by paulvi** [comment]
@yasserzamani This is now #54

**Pull request merged**
