### PR TITLE
Clarifies how to access parameters

### PR DESCRIPTION
**Pull request by lukaszlenart**

### CODE REVIEW

**Comment by lukaszlenart** [comment]
@gregh3269 could you review

**Comment by gregh3269** [comment]
It has:

You can access such params without using JSTL, just use ${param.ParamName} notation in Struts tags.

Its not very clear "in Strust tags".  I don't think you can use ${param.ParamName} **inside** struts tags because its a runtime expression.  I think its only between ><.

eg

```
<s:include value="myJsp.jsp">
  <s:param name="ParamName">world</s:param>
</s:include>

myJsp.jsp

<s:set var="paramName" scope="page">${param.ParamName}</s:set>
<s:if test='%{#attr.paramName == "world"}'>
  Hello World
</s:if>

You cannot do this as its an expression ("test" does not support runtime expressions)
<s:if test='${param.ParamName} == "world"'>
  Hello World
 </s:if>
```

(Also the camel case could be better param.ParamName >> param.paramName)

Possibly why they give up and use jstl as it just works ;-)

**Comment by lukaszlenart** [comment]
Thanks for review, changed the text a bit. Should I also include a note about using `#attr.paramName`?

**Comment by gregh3269** [comment]
I would include an example if possible, examples are better than words.  This would save some head scratching!!

On your example :

<s:set var="paramName" scope="page">${param.paramName}</s:set>
<s:property value="paramName"/>

I think its better to have the #attr always, but for scope="page" its required

with scope:
<s:set var="paramName" scope="page">${param.paramName}</s:set>
<s:property value="#attr.paramName"/>

with no scope:
<s:set var="paramName">${param.paramName}</s:set>
<s:property value="#attr.paramName"/>
<s:property value="#paramName"/>
<s:property value="paramName"/>

**Comment by lukaszlenart** [comment]
How about now?

**Comment by gregh3269** [comment]
missed one #attr.  first one on the page

<s:set var="paramName" scope="page">${param.paramName}</s:set>
<s:property value="paramName"/>

...this would be a good interview question lol

**Comment by lukaszlenart** [comment]
Got it, now it should be ok :)

**Comment by gregh3269** [comment]
Looks good.  .

...I remember a while back when I was trying to speed up my pages, think the page scope was checked first, so that's why I always include the #attr.  (Not sure on the order on the #innerName variable?)  Would this assumption be correct?  The order then could be like below.  

<s:property value="#attr.innerName"/>
<s:property value="#innerName"/>
<s:property value="innerName"/>

**Comment by lukaszlenart** [comment]
I think this somehow clarifies the order, `#attr.param` and `#param` should be threaten the same
https://struts.apache.org/core-developers/accessing-application-session-request-objects#accessing-from-the-view-jsp-freemarker-etc

**Comment by gregh3269** [comment]
The s:set tag mentions

NOTE: If no scope is specified, it will default to action scope. For the set tag specifically, this also places (sets) the generated value into the page scope as well (retrieve via #attr).

So for no scope it also places one in the page scope, but if you don't specify #attr ie

<s:property value="paramName"/>

What would happen here?  Get if from the action?

When I was testing with a huge page of sets and the #attr. made a difference.

**Comment by lukaszlenart** [comment]
`<c:set/>` tag pushes a value on top of the ValueStack and `<s:property/>` reads from VS. So if the value is on top of VS then it will be used, no search down the stack is performed. `#attr` searches the whole stack.

**Comment by gregh3269** [comment]
Worth remembering (and there is alot on this).  Think I was only testing s:if for work fields, most of my fields are in the beans.

Think we should be OK here (as I have gone a bit off topic).

**Comment by lukaszlenart** [comment]
Great, I will merge this PR but I think clarifying how `#` & `#attr` works, will open another PR :)

**Pull request merged**
