### PR TITLE
Update plugins.md

### PR DESCRIPTION
**Pull request by jeffblack360**
Render "Extension Points" HTML table properly

### CODE REVIEW

**Comment by yasserzamani** [comment]
I'm aware about this known issue; Deleting ``` doesn't solve it and shows a mixed up raw html table :( I don't know why Jekyll does this! Maybe because it's a huge table. Maybe converting it to a markdown table solve this issue.

**Comment by lukaszlenart** [comment]
Yeah... I have no idea why it happens, probably some built-in escaping mechanism

**Comment by jeffblack360** [comment]
According to the Markdown docs HTML tables will be rendered correctly and looked fine on preview.

**Comment by lukaszlenart** [comment]
What did you use to preview it, our docker image?

**Comment by jeffblack360** [comment]
No sir, just the preview in Github. Does it render differently?

**Comment by lukaszlenart** [comment]
Yeah... looks like but we can merge it, maybe something has changed

**Comment by jeffblack360** [comment]
OK. I didn't realize it rendered differently, considering that it's edited directly in Github.

**Comment by lukaszlenart** [comment]
Yes, but we do not use `gh-pages` nor any GitHub mechanism to convert a `.md` file into a html page.

**Comment by jeffblack360** [comment]
Got you. I have worked on CakePHP docs directly on Github and assumed it was the same.

**Comment by yasserzamani** [comment]
> Yeah... looks like but we can merge it, maybe something has changed

Yeah... let's see what happens , if not resolved I'll convert this table to markdown with a few regex replaces 😉

**Comment by jeffblack360** [comment]
You guys were right. The HTML is goofy now. Can you revert the change?

**Comment by yasserzamani** [comment]
No problem :) I proposed a fix by #102 which will convert html table to markdown via a few regex replaces.

Thanks for your report 👍

**Comment by yasserzamani** [comment]
@jeffblack360 , fixed :) please see [here](http://struts.apache.org/plugins/plugins).

**Comment by jeffblack360** [comment]
Thank you sir!  Great work. I see how you create the table now. Lesson learned!

**Pull request merged**
