### PR TITLE
rename files: "Release Guidelines" to /release-guidelines.html and

### PR DESCRIPTION
**Pull request by paulvi**
rename files: "Release Guidelines" to /release-guidelines.html and "Releases" to /releases.html

ref https://github.com/apache/struts-site/pull/48#issuecomment-349841482

Download `/download` for link to current release that users needs to download.

Releases `/downloads` all current and previous releases as releases history.
- [ ] Not intended for downloads, so better to rename file as its title to /releases

"Release Guidelines" `/releases.html`  
- [ ] rename it to release-guidelines

### CODE REVIEW

**Comment by paulvi** [comment]
oops, menu needs update...

**Comment by paulvi** [comment]
please review

**Comment by lukaszlenart** [comment]
Conflict :(

**Comment by paulvi** [comment]
resolved

**Comment by lukaszlenart** [comment]
👍

**Pull request merged**
