### PR TITLE
SCM Disambiguation

### PR DESCRIPTION
**Pull request by dotun**
Is this Source Control Management or Source Configuration Management.

### CODE REVIEW

**Comment by yasserzamani** [comment]
When I read next sentences to SCM, I feel both are OK and doesn't matter.

**Comment by lukaszlenart** [comment]
I would say `Source Control Management`

**Comment by dotun** [comment]
@lukaszlenart, I've made it Source Control Management as suggested. Kindly review.

**Comment by lukaszlenart** [comment]
Thanks, LGTM 👍

**Pull request merged**
